### PR TITLE
Created edit profile page

### LINKED ISSUE #6: Edit User Profile Page
## Description

We need to be able to edit a user's details after their profile has been created. Something like instagram's UI, I'd imagine - a little edit button on their profile leads to a page which vaguely like the user profile page, but where everything is editable. 

## Spec

- [ ] Change / set profile photo
- [ ] Change bio
- [ ] Accessible from user bio, leads back to user profile

### PR DESCRIPTION
**Pull request by maxpinheiro**
## Description
Created a modal window for the profile page that allows for editing the user's information (profile picture, username, first name, last name, bio). The picture is currently saved in both base64 and buffer format. The window is accessible from the profile page, and the "Done" button returns to the profile page.

Closes #6 

## Screenshot
edit_profile

### CODE REVIEW

**Review by ross3102 — CHANGES_REQUESTED** [review]
On Android with Dark Mode enabled, entered text doesn't show up on the Edit Profile screen

photo_2022-02-14_12-19-40

**Comment by nicoledanuwidjaja** [comment]
> On Android with Dark Mode enabled, entered text doesn't show up on the Edit Profile screen
> 
> photo_2022-02-14_12-19-40

Thank you Mr. dark mode! The 'done' button also looks a bit strange on Android too; I can look into that.

**Comment by connorlbark** [comment]
okay, I tried to run this on android simulator and for some reason the app would just hang indefinitely (all other apps in the simulator worked?) but I'm going to to assume this is a simulator issue not a code issue.

**Review by connorlbark — APPROVED** [review]
right now, dark mode also looks weird on iOS - the borders being black always leads to everything blending together. but it's ok - this isn't our final design anyway, so i'll go ahead and approve it.

**Comment by ross3102** [comment]
> okay, I tried to run this on android simulator and for some reason the app would just hang indefinitely (all other apps in the simulator worked?) but I'm going to to assume this is a simulator issue not a code issue.

Works on Android, looks good to me!

**Review by ross3102 — APPROVED** [review]
Looks good!

**Pull request merged**
